version: '3.9'

services:
  postgres:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - config/.env
    ports:
      - '5432:5432'
    container_name: postgres
  
volumes:
  postgres_data: